---
title: "Traditional Society"

---

## Characteristics of Medieval Society

1.  The Medieval West was as poor if not poorer economically than the
    other world civilizations. Medieval society was an overwhelmingly
    **agricultural** society [@rosenberg_birdzell86 38]. While the
    modern world is "irretrievably urban" traditional society was
    "unmistakably rural" [@rosenberg_birdzell86 40].

2.  The Medieval West lacked mass communication, finance and banking,
    and merchants played a small role in the economy. Factories were
    non-existent, most production was either small-scale guild
    production in the towns or relatively isolated large-scale
    production in the manor. Most product was used on the spot.
    Production for export to foreign territories was minimal
    [@rosenberg_birdzell86 37].

3.  The Medieval West knew **no distinction between political and
    economic authority**; in the country the lord ruled his manor. In
    the city, guilds were autocratically run by guild masters
    [@rosenberg_birdzell86 38]. Serfs owed political obeisance to the
    *seignur* (lord) as well as being economically dependent on him. The
    distinction between political and economic power was simply unknown
    [@rosenberg_birdzell86 41].

4.  **Terms of trade were not established through market mechanisms.**
    Instead "custom, usage and law" not "negotiation" and markets
    governed the economy (e.g. prices, allocation of labor and
    productive factors, etc.).

6.  Agricultural workers were bound to the land by a system of serfdom,
    which was a hereditary status (you were born a serf and died a serf
    with no opportunity for "mobility").

7.  Markets (for labor, products and factors) were suffused with
    morality. The notion of a morally neutral market was non-existent.
    Rules against raising prices or against charging interest were
    enforced by a combination of moral and religious condemnation.

8.  Economic interdependencies were minimal; the basic production unit
    was the manor and manors were self-sufficient. "Global" coordination
    of production enterprises was comparatively under-developed.

9.  The **money economy** was underdeveloped and in many ways
    non-existent. Most exchange took the form of barter and the exchange
    of labor for products. **Labor, product, land and factor markets
    were highly restricted**. Workers in a manor could not just pick up
    and work for some other lord; guild-workers were bound to the
    authority of the guild and labor market were socially and
    geographically restricted. Guild workers restricted the prices at
    which all commodities were to be sold and bought.

10. Wage labor existed, but was very restricted (to the guilds in the
    towns) and even there restrictions on the mobility of labor were
    severe. Traditional restrictions against exchanging various goods
    and services for money were strong. "Usury" (the lending of money
    for a profit in the form of interest was regarded as sin).

11. Economic activity was not guided or governed by "rational"
    considerations as we understand it. The notion of economic
    calculation of risk and benefits and of profit was alien to the
    Medieval mind. Instead custom, tradition and law dominated business
    and economic activity. Markets for credit and money were
    non-existent. The idea of applying rational techniques of risk
    assessments for the introduction of new technology or even the
    notion of maximizing production was non-existent.

## Culture and Mentality

1. At the social level status divisions and hierarchy dominated social
    relations. Inferiors were expected to show outward deference and
    respect for their status superiors, and superiors were likely to
    expect and enforce this deference.

2. Ideas of individual "rights" were non-existent. Only collective or
    group rights were recognized.

3. The conception of privacy was underdeveloped and in many ways
    non-existent. Bodily excretions and bodily functions were out there
    for everybody to see. Notions related to "manners" and "decorum"
    were underdeveloped. Violence was rampant. Death was a public not a
    Private event.

4. Cruel punishment and violence were the name of the game. Modern
    notions of "compassion" and caring for others in general were
    non-existent.

5. Magic and superstition suffused everyday life. The world was seen as
    populated with a host of supernatural entities.

6. The institutionalization of the criminal and the "insane" was
    generally minimal.
    
## Discussion Questions
- What characteristics of traditional (medieval society) struck you as most radically different from contemporary society?
- What part of the description of Medieval society did you find surprising? Why?
- Is there any aspect of Medieval society that you think we should go back to?
- What aspects of Medieval society do you see as continuous to modern society
