# Weber: The Different Roads to Salvation {#weber-action-interests}

## Why do people do the things they do?
A key problem for Max Weber concerns the **motivation** for human action.  This was not a problem for Marx, because he had a strong theory of human nature that answered that question for him (persons are motivated to produce their means of subsistence through creative activity).  For Weber on the other hand, human nature is culturally pliable and thus motivations are culturally arbitrary (and thus problematic). 

Weber focuses on **religion** because he sees this **life sphere** as being primary in terms of setting down fundamental motivations for human action (other life spheres like the economy actually *inherit* motivational templates from the religious one as we will see later). Weber sees the quest for salvation as the prototypical example of motivated action. For Weber unmotivated action is not social action, while motivated action is inherently social.

Religious action is motivated action because it is action that is done with an explicit purpose in mind.  In so-called "salvation" religions this purposive nature of religious conduct is brought to the fore with clarity.  For instance the purpose of ritual can be the "cleansing" of the person from sin, or the production of a particular mood.

## Material versus Ideal Interests
The key difference between Marx and Weber concerns the substantive content of motivation.  For Weber, the standard Marxian account is concerned exclusively with action motivated by what he refers to as **material interests**.  The Marxian model in which action and ideas are directly determined by social position "works" because in the case of material interests there is a one-to-one correspondence between interests and position, so the analyst can "predict"  one from the other.  Weber is interested instead in cases in which action appears to be motivated by **ideal interests**.  Ideal interests appear irrational from a Marxian model because they seem to go against the person's material interests. 

Ideal interests for instance, are involved in action that is clearly altruistic or that leads the person to forgo material advantage.  Ideal interests are also involved in action that, while being "self interested" (e.g. the quest for salvation) requires otherwise inexplicable (and sometime extreme) sacrifices of material and social goods. When confronted with cases in which action is motivated by ideal interests, the analyst cannot engage in the Marxian heuristic of reading the motivation of action directly from the requirements imposed by objective social position. Instead, when dealing with ideal interests the analyst must engage in the *rational reconstruction of the motivation of action*, or else deem the action "irrational."  For Weber, such a charitable reconstruction of action as rational necessarily involve reference to the *analytically independent power of ideas* as a *sui generis* motivator of action, not simply as a reflection of social position.

## Religion and Life Conduct

Weber thought that he could use the different motivations for action evident in the history of the world religions to show that ideas had a specific effect on the direction of action.  For instance, different religions set up different "accounting systems" for the achievement of salvation. Some like Zoroastrianism,  good and bad actions independently of one another, giving more important to the "net total" achieved during the person's lifetime.  Others, like **ascetic Protestantism** enforce a strict accounting where no deviation is allowed. Medieval Catholicism enforces a ritualistic cleansing of bad actions as mediated by the ritual of confession officiated by the priest, and so on.

The social consequences of a given religious system for action outside of the religious realm depend on how the path to salvation is defined.  For instance extreme ritualism (e.g., Hinduism) depresses rational economic action.  In this respect extreme ritualism is the opposite of puritan asceticism.

**Ritualism** of any kind can also depress rational activity because its consequences do not "carry over" to other realms; they are simply meant to produce short-term "moods."  When ritualism does become a consistent part of a person's everyday existence it usually leads to mysticism.

The goal of salvation can lead to all kinds of action performances, including sacrifice in battle, schooling, and the performance of "good works." In this way, religious motivations may carry over into other realms or spheres of life.

An ethic of good works leads to a logic of "accounting" but it does not lead to the *systematization* of ethical action: instead "the conduct of life remains, from the viewpoint of ethics, and unmethodical and miscellaneous succession of discrete actions" (p. 155).

The primary goal of most religious activity is the attainment of a particular ethical or emotional state. When God is conceptualized as being **immanent** to the world (or in religious without a transcendental God), the goal of religious activity is ethical self perfection and self-deification. In religions with a **transcendental God** (a deity that is seen as separate and outside the world), the goal of religious activity "must become the acquisition of those religious qualities the god demands in men" (p. 159).

The primary problem of all salvation religions, according to Weber, is the problem of certainty. Essentially the question of "how do you know for sure that you are saved" becomes the primary observation of believers.  This leads persons to an endless quest for a particular psychological state that Weber refers to as *certitudo salutis* (the certainty or assurance of grace). Weber sees most of the extreme forms of religious practices as being means to the attainment of this psychological state:
	
> Thus, all of these methodologies of sanctification developed a combined physical and psychic regimen and an equally methodical regulation of the manner and scope of thought and action, thus producing in the individual the most completely alert, voluntary, and anti-instinctual control over his [sic] own physical and psychological processes, and insuring teh systematic regulation of life in subordination to the religious end (p. 162).
	
Any religion that sets up "requirements" and "procedures" for salvation, also generates a "stratification" or "differentiation" of persons based on their ability to meet those requirements (p. 162). One of the most common "methodical techniques" of religion to create differentiation are those that recommend "the transcendence of particular desires and emotions of raw human nature."  This differentiates between persons who are able to do that (and thus acquire **charisma**) and the rest who cannot do those particular extraordinary actions.

Weber notes that a particular way of thinking about what it takes to achieve salvation leads to an attitude that he calls **ascetic** in this case salvation is "viewed as the distinctive gift of active ethical behavior performed in the awareness that god directs this behavior" (p. 164).

## Assignment
**Instructions**.- As we have seen, in contrast to Marx who claimed that social position determined ideas, Weber argues for the independent effect of ideas on social action.  Weber reasoned that the best way to demonstrate this effect of ideas on social action was through the analysis of lines of conduct that would appear to be irrational if it were not for our capacity to reconstruct the motivations for that type of action by appealing to the person's belief system.  For this assignment, I want you to take a piece of behavior that is seemingly irrational, and *make it understandable* by reconstructing the actors motivation and their belief system.  Make sure to be specific and to pay attention to the details of your example. 